yacup: Interface
Interface
Utilities » Command Engine
Description
Complete API documentation for finite state machine setup, instantiation and usage.
Complete API documentation for command engines setup, instantiation and usage. This will help to familiarize with commands (signature, validation, argument, listener...), subsets of commands (allow to create different commands dictionaries for different scenarios) and sets of subsets (a specific full composed dictionary a specific command engine will be able to send or receive)
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Data Structures
struct ce_channel
Structure that defines a command engine channel.
struct ce_codec_encoder
Structure that defines a ce codec encoder operations.
struct ce_codec_decoder
Structure that defines a ce codec encoder operations.
struct ce_codec
Structure that defines a ce codec operations.
struct ce_command_argument
Structure that defines a command argument.
struct ce_command_listener
Structure that defines a command listener with its storage.
struct ce_command
Structure that defines a command.
struct ce_command_subset
Structure that defines a subset of commands.
struct ce_command_set
Structure that defines a set of commands (composed by subsets)
struct ce_driver
Structure that defines the input/output chat between parties (communication protocol)
union ce_data
Storage and namings for supported data types in a command engine.
struct ce
Structure that defines a command engine.
Enumerations
enum ce_data_type {
CE_DATA_NULL, CE_DATA_UINT8_T, CE_DATA_INT8_T, CE_DATA_UINT16_T,
CE_DATA_INT16_T, CE_DATA_UINT32_T, CE_DATA_INT32_T, CE_DATA_UINT64_T,
CE_DATA_INT64_T, CE_DATA_FLOAT, CE_DATA_DOUBLE
}
Supported data types in a command engine.
Functions
int ce_channel_init (struct ce_channel *channel, int(*channels_codec_driver_init)(struct ce_codec *), int(*channels_rb_driver_init)(struct rb *))
Initializes a command engine channel using lower level inits.
int ce_codec_init (struct ce_codec *codec, int(*ce_codec_driver_init)(struct ce_codec *))
Initializes a ce_codec
struct ce_command * ce_command_locate_by_id (struct ce_command_set *cmd_set, size_t id)
Locate a command in a set by its unique identifier.
struct ce_command * ce_command_validate (struct ce_command_set *cmd_set, size_t id, struct ce_command_argument *argument[])
Checks if passed command is found on set and has valid arguments.
int ce_command_set_listener (struct ce_command_set *cmd_set, size_t id, struct ce_command_listener *listener)
Set a command listener, if found in a set.
int ce_init (struct ce *ce, int(*ce_driver_init)(struct ce *), int(*channels_codec_driver_init)(struct ce_codec *), int(*channels_rb_driver_init)(struct rb *))
Initializes a command engine referenced by a ce pointer.
int ce_tick (struct ce *ce)
Executes a command engine chat fsm cycle. Required if data is expected to be received and/or parsed.
int ce_send_command (struct ce *ce, size_t id, struct ce_command_argument *argument[])
Validates if a command is found in a set, and if it pass the signature check, then encode its data into a message and send it.
int ce_wait_command (struct ce *ce, size_t *id, struct ce_command_argument **argument[])
Function Documentation
ce_channel_init()
int ce_channel_init (struct ce_channel * channel, int(*)(struct ce_codec *) channels_codec_driver_init, int(*)(struct rb *) channels_rb_driver_init)
#include <channel.h>
Initializes a command engine channel using lower level inits.
Prepares and initializes the channel: command set, codec and codec message buffer
Parameters
channel Poiner to channel to initialize
channels_codec_driver_init Channel codec driver initializer
channels_rb_driver_init Message rb driver initializer
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 29 of file channel.c.
References _dbg, ce_codec_init(), ce_channel::codec, ce_channel::command_set, ce_channel::data, ce_channel::message, and rb_init().
Referenced by ce_init().
ce_codec_init()
int ce_codec_init (struct ce_codec * codec, int(*)(struct ce_codec *) ce_codec_driver_init)
#include <codec.h>
Initializes a ce_codec
Checks and initializes ce_codec common data, then calls the lower level init function passed by argument. The latter is defined at each ce_codec unit, and it is where the encoding and decoding functions are really assigned.
Parameters
codec Pointer to a codec to initialize
ce_codec_driver_init The ce codec driver initializer function
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 29 of file codec.c.
References _dbg, ce_codec_encoder::command, ce_codec_decoder::command, ce_codec_encoder::data, ce_codec_decoder::data, ce_codec::decode, ce_codec::encode, ce_codec_encoder::message, ce_codec_decoder::message, and ce_codec::name.
Referenced by ce_channel_init(), test_ce_codec_B416K(), and test_ce_command_codec_B416K().
ce_command_locate_by_id()
struct ce_command* ce_command_locate_by_id (struct ce_command_set * cmd_set, size_t id)
#include <command.h>
Locate a command in a set by its unique identifier.
Parameters
cmd_set Set of commands where to search for commands
id Unique command identifier of the command to validate
Returns
One of:
Value Meaning
== NULL Command not valid
!= NULL Pointer to valid command
Definition at line 29 of file command.c.
References _dbg, and ce_command_set::name.
Referenced by ce_command_validate().
ce_command_validate()
struct ce_command* ce_command_validate (struct ce_command_set * cmd_set, size_t id, struct ce_command_argument * argument[])
#include <command.h>
Checks if passed command is found on set and has valid arguments.
Parameters
cmd_set Set of commands where to search for commands
id Unique command identifier of the command to validate
argument Arguments to check against command signature
Returns
One of:
Value Meaning
== NULL Command not valid
!= NULL Pointer to valid command
Definition at line 81 of file command.c.
References _dbg, ce_command_locate_by_id(), ce_command::id, ce_command::name, ce_command_set::name, and ce_command::signature.
Referenced by ce_command_set_listener(), ce_send_command(), and test_ce_command_codec_B416K().
ce_command_set_listener()
int ce_command_set_listener (struct ce_command_set * cmd_set, size_t id, struct ce_command_listener * listener)
#include <command.h>
Set a command listener, if found in a set.
Parameters
cmd_set Set of commands where to search for commands
id Unique command identifier of the command to send
listener Incoming command listener
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 161 of file command.c.
References _dbg, ce_command_listener::argument, ce_command_validate(), and ce_command::listener.
Referenced by test_ce_driver_faf(), and test_ce_initialization().
ce_init()
int ce_init (struct ce * ce, int(*)(struct ce *) ce_driver_init, int(*)(struct ce_codec *) channels_codec_driver_init, int(*)(struct rb *) channels_rb_driver_init)
#include <ce.h>
Initializes a command engine referenced by a ce pointer.
Checks and initializes ce common data, then calls the lower level init function passed by argument.
Parameters
ce Pointer to a CE to initialize
ce_driver_init ce driver to handle this CE
channels_codec_driver_init ce_codec to use for data/messages
channels_rb_driver_init rb driver to handle channels RB
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 29 of file ce.c.
References _dbg, ce_channel_init(), ce::in, ce::name, and ce::out.
Referenced by test_ce_driver_faf(), and test_ce_initialization().
ce_tick()
int ce_tick (struct ce * ce)
#include <ce.h>
Executes a command engine chat fsm cycle. Required if data is expected to be received and/or parsed.
Parameters
ce Pointer to the command engine to tick
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
ce_send_command()
int ce_send_command (struct ce * ce, size_t id, struct ce_command_argument * argument[])
#include <ce.h>
Validates if a command is found in a set, and if it pass the signature check, then encode its data into a message and send it.
Parameters
ce Pointer to the engine that will handle this command
id Unique command identifier of the command to send
argument Arguments to check against command signature and send
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 71 of file ce.c.
References _dbg, ce_command_validate(), ce_channel::command_set, ce::driver, ce::out, and ce_driver::send_command.