yacup: Utilities tests
Utilities tests
Tests
Description
Available tests for utilities (util folder)
Utilities are found inside util folder and it will depends only on foreign libraries or something found inside util folder, but not from src one (as this is an application)
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Functions
int test_ce_codec_B416K (int argc, const char *argv[])
Test to check ce functionality using a single ce.
int test_ce_command_codec_B416K (int argc, const char *argv[])
Test to check ce functionality using a single ce.
int test_ce_command_validate (int argc, const char *argv[])
Test to check ce functionality using a single ce.
int test_ce_driver_faf (int argc, const char *argv[])
Test to check ce functionality using a single CE.
int test_ce_initialization (int argc, const char *argv[])
Test to check ce functionality using a single ce.
int test_fsm_driver_simple (int argc, const char *argv[])
Test to check fsm functionality using a single fsm.
int test_rb_driver_overwrite (int argc, const char *argv[])
Tests overwrite driver API and functionality.
Function Documentation
test_ce_codec_B416K()
int test_ce_codec_B416K (int argc, const char * argv[])
#include <test_ce_codec_B416K.c>
Test to check ce functionality using a single ce.
Parameters
[in] argc The count of arguments
argv The arguments array
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Version
v1.0.0
Definition at line 216 of file test_ce_codec_B416K.c.
References _dbg, rb::buffer, ce_codec_B416K(), ce_codec_init(), ce_codec_print_info(), rb_driver_overwrite(), and rb_init().
Referenced by test_yacup().
test_ce_command_codec_B416K()
int test_ce_command_codec_B416K (int argc, const char * argv[])
#include <test_ce_command_codec_B416K.c>
Test to check ce functionality using a single ce.
Parameters
[in] argc The count of arguments
argv The arguments array
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Version
v1.0.0
Definition at line 50 of file test_ce_command_codec_B416K.c.
References _dbg, rb::buffer, ce_codec_B416K(), ce_codec_init(), CE_COMMAND_SET_TEST_CMD5, ce_command_validate(), ce_codec_encoder::command, ce_codec::encode, ce_command_set::name, ce_codec::name, rb_driver_overwrite(), rb_init(), rb_print_info(), test_command_subset_part_A, test_command_subset_part_B, and ce_command_argument::type.
Referenced by test_yacup().
test_ce_command_validate()
int test_ce_command_validate (int argc, const char * argv[])
#include <test_ce_command_validate.c>
Test to check ce functionality using a single ce.
Parameters
[in] argc The count of arguments
argv The arguments array
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Version
v1.0.0
Definition at line 44 of file test_ce_command_validate.c.
References _dbg, ce_command_set::name, test_command_subset_part_A, test_command_subset_part_B, and ce_command_argument::type.
Referenced by test_yacup().
test_ce_driver_faf()
int test_ce_driver_faf (int argc, const char * argv[])
#include <test_ce_driver_faf.c>
Test to check ce functionality using a single CE.
Parameters
[in] argc The count of arguments
argv The arguments array
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Version
v1.0.0
Definition at line 52 of file test_ce_driver_faf.c.
References _dbg, ce_codec_B416K(), ce_command_set_listener(), CE_COMMAND_SET_TEST_CMD1, ce_driver_faf(), ce_init(), ce_channel::data, ce::name, ce::out, rb_driver_overwrite(), rb_print_info(), test_cmd1_listener, test_command_set, and ce_command_argument::type.
Referenced by test_yacup().
test_ce_initialization()
int test_ce_initialization (int argc, const char * argv[])
#include <test_ce_initialization.c>
Test to check ce functionality using a single ce.
Parameters
[in] argc The count of arguments
argv The arguments array
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Version
v1.0.0
Definition at line 50 of file test_ce_initialization.c.
References _dbg, ce_codec_B416K(), ce_command_set_listener(), CE_COMMAND_SET_TEST_CMD1, ce_driver_faf(), ce_init(), ce::name, rb_driver_overwrite(), test_cmd1_listener, test_command_set, and ce_command_argument::type.
Referenced by test_yacup().
test_fsm_driver_simple()
int test_fsm_driver_simple (int argc, const char * argv[])
#include <test_fsm_driver_simple.c>
Test to check fsm functionality using a single fsm.
Parameters
[in] argc The count of arguments
argv The arguments array
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Version
v1.0.0
Definition at line 46 of file test_fsm_driver_simple.c.
References _dbg, fsm_do_cycle(), fsm_driver_simple(), fsm_enable(), fsm_init(), fsm_print_info(), fsm_print_stats(), fsm_request_start(), fsm_set_loop(), and fsm::name.
Referenced by test_yacup().
test_rb_driver_overwrite()
int test_rb_driver_overwrite (int argc, const char * argv[])
#include <test_rb_driver_overwrite.c>
Tests overwrite driver API and functionality.
Parameters
[in] argc The count of arguments
argv The arguments array
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Version
v1.0.0
Definition at line 46 of file test_rb_driver_overwrite.c.
References _dbg, rb::buffer, rb_driver_overwrite(), rb_full(), rb_init(), rb_len(), rb_print_info(), rb_pull(), rb_push(), rb_read(), rb_reset(), and rb_write().
Referenced by test_yacup().