yacup: Application tests
Application tests
Tests
Description
Available tests for applications (src folder)
Applications are found inside src folder and it will normally depends on something found on util folder (but it is not mandatory)
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Functions
int test_yacup (int argc, const char *argv[])
The main of the mains.
Function Documentation
test_yacup()
int test_yacup (int argc, const char * argv[])
#include <test_yacup.c>
The main of the mains.
Parameters
[in] argc The count of arguments
argv The arguments array
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Version
v1.0.0
Definition at line 51 of file test_yacup.c.
References _dbg, test_ce_codec_B416K(), test_ce_command_codec_B416K(), test_ce_command_validate(), test_ce_driver_faf(), test_ce_initialization(), test_fsm_driver_simple(), and test_rb_driver_overwrite().