yacup: Overwrite
Overwrite
Utilities » Ring-buffer » Available drivers
Description
First rb driver implementation, overwrite if full.
This implementation will overwrite data if full, updating both head and tail indices without throwing an error.
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Functions
int rb_driver_overwrite (struct rb *rb)
Driver initializer function for overwrite RB driver.
Function Documentation
rb_driver_overwrite()
int rb_driver_overwrite (struct rb * rb)
#include <overwrite.h>
Driver initializer function for overwrite RB driver.
Lowest level checks, variables and operations assignment to rb
This set of operations belongs to a first driver implementation, where a ring-buffer tail byte is overwritten if pushing over a full rb. This operation is performed without any warning or error.
If it is needed to preserve data under this circumstances, a new driver have to be implemented.
Parameters
rb Pointer to a rb to work with
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 207 of file overwrite.c.
References _dbg, rb::driver, rb_driver::full, rb_driver::len, rb_driver::name, rb_driver::pull, rb_driver::push, rb_driver::read, rb_driver::reset, rb_driver::size, rb_driver::validate, and rb_driver::write.
Referenced by test_ce_codec_B416K(), test_ce_command_codec_B416K(), test_ce_driver_faf(), test_ce_initialization(), and test_rb_driver_overwrite().