yacup: Fire and Forget
Fire and Forget
Utilities » Command Engine » Available drivers
Description
A ce chat that send/receive data without confirmation.
Todo:
Write a description/@details
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Data Structures
struct ce_driver_faf_data
Internal data ce_driver_faf will use.
Macros
#define CE_DRIVER_FAF_FSM_DELAY_MS 50
Dead time applied when cycling the fsm so the CPU is not locked.
#define CE_DRIVER_FAF_SEND_TIMEOUT_MS 1000
Timeout when sending.
#define CE_DRIVER_FAF_RECEIVE_TIMEOUT_MS 1000
Timeout when receiving.
Functions
int ce_driver_faf (struct ce *ce)
Driver initializer function for ce_driver_faf type CE.
FSM States
static int s_start (struct fsm *fsm)
Prepare extra variable.
static int s_wait_cmd (struct fsm *fsm)
Stay here during 5 counts of extra variable.
static int s_encode (struct fsm *fsm)
Encode command + data as a message.
static int s_decode (struct fsm *fsm)
Encode command + data as a message.
static int s_send (struct fsm *fsm)
Send the message to the outside world.
static int s_receive (struct fsm *fsm)
Receive data and saves it.
static int s_error (struct fsm *fsm)
Some error happened. Wops!
static int s_stop (struct fsm *fsm)
Prepare anything before stopping the fsm.
Function Documentation
s_start()
static int s_start (struct fsm * fsm) static
#include <fire-and-forget.c>
Prepare extra variable.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 69 of file fire-and-forget.c.
References fsm::next, s_error(), and s_wait_cmd().
s_wait_cmd()
static int s_wait_cmd (struct fsm * fsm) static
#include <fire-and-forget.c>
Stay here during 5 counts of extra variable.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 113 of file fire-and-forget.c.
References fsm::next, s_encode(), and s_receive().
Referenced by s_start().
s_encode()
static int s_encode (struct fsm * fsm) static
#include <fire-and-forget.c>
Encode command + data as a message.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 150 of file fire-and-forget.c.
References _dbg, ce_channel::codec, ce_codec_encoder::command, ce_channel::data, ce_codec::encode, ce_channel::message, ce_codec_encoder::message, fsm::next, ce::out, rb_print_info(), s_error(), and s_send().
Referenced by s_wait_cmd().
s_decode()
static int s_decode (struct fsm * fsm) static
#include <fire-and-forget.c>
Encode command + data as a message.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 202 of file fire-and-forget.c.
References _dbg, ce_channel::codec, ce_codec_decoder::command, ce_channel::command_set, ce_channel::data, ce_codec::decode, ce::in, ce_channel::message, ce_codec_decoder::message, fsm::next, rb_print_info(), s_error(), and s_stop().
Referenced by s_receive().
s_send()
static int s_send (struct fsm * fsm) static
#include <fire-and-forget.c>
Send the message to the outside world.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 257 of file fire-and-forget.c.
References _dbg, fsm::next, and s_stop().
Referenced by s_encode().
s_receive()
static int s_receive (struct fsm * fsm) static
#include <fire-and-forget.c>
Receive data and saves it.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 289 of file fire-and-forget.c.
References _dbg, fsm::next, and s_decode().
Referenced by s_wait_cmd().
s_error()
static int s_error (struct fsm * fsm) static
#include <fire-and-forget.c>
Some error happened. Wops!
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 320 of file fire-and-forget.c.
References _dbg, fsm::name, fsm::next, and s_stop().
Referenced by s_decode(), s_encode(), and s_start().
s_stop()
static int s_stop (struct fsm * fsm) static
#include <fire-and-forget.c>
Prepare anything before stopping the fsm.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 351 of file fire-and-forget.c.
Referenced by s_decode(), s_error(), and s_send().
ce_driver_faf()
int ce_driver_faf (struct ce * ce)
#include <fire-and-forget.h>
Driver initializer function for ce_driver_faf type CE.
This chat FSM will control input and output operations on a fire and forget type protocol, where the data is sent without any confirmation expectation or timeout, and when data is received there is no feedback to the remitent. It is the easiest form of protocol, where everything is supposed to be perfect, with no communication errors
Parameters
ce Pointer to a ce to work with
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 567 of file fire-and-forget.c.
References _dbg, CE_DRIVER_FAF_FSM_DELAY_MS, CE_DRIVER_FAF_RECEIVE_TIMEOUT_MS, CE_DRIVER_FAF_SEND_TIMEOUT_MS, fsm::data, ce::driver, ce_driver::fsm, fsm_enable(), fsm_init(), fsm_print_info(), fsm_request_start(), fsm_set_loop(), ce::name, ce_driver::send_command, and ce_driver::wait_command.
Referenced by test_ce_driver_faf(), and test_ce_initialization().