yacup: Debug functions
Debug functions
Debug and development
Description
Debugging helper functions to ease the development flow.
Each util or app is responsible of create or not a debug function, but it is recommended to invest a bit of time to create them, and the more the verbose, the better
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Macros
#define _dbg(...)
Macro used to unify debugging messages.
Functions
void ce_print_info (struct ce *ce)
Print ce information to STDOUT.
void ce_codec_print_info (struct ce_codec *codec)
Print ce_codec information to STDOUT (encode/decode functions)
void fsm_print_info (struct fsm *fsm)
Print fsm information to STDOUT (name, config, state, ...)
void fsm_print_stats (struct fsm *fsm)
Print fsm stats to STDOUT (how many times each run-state has been executed/cycled)
void rb_print_info (struct rb *rb)
Print rb information to STDOUT (size, head, tail, ...)
Macro Definition Documentation
_dbg
#define _dbg (...)
#include <debug.h>
Macro used to unify debugging messages.
This is a configurable macro:
If YACUP_DEBUG is defined, PRINTF macro will be used.
If PRINTF is not defined, standard printf will be used.
User can define PRINTF as a custom function. As example, instead of print to stdout, the string is sent through a serial port.
If YACUP_DEBUG is not defined, no debug function is used and no string storage allocation is performed.
Note
Read yacup/debug.h for complete information
Definition at line 61 of file common/yacup/debug.h.
Function Documentation
ce_print_info()
void ce_print_info (struct ce * ce)
#include <debug.h>
Print ce information to STDOUT.
Parameters
ce Pointer to a valid ce
Definition at line 33 of file ce/debug.c.
References _dbg.
ce_codec_print_info()
void ce_codec_print_info (struct ce_codec * codec)
#include <debug_codec.h>
Print ce_codec information to STDOUT (encode/decode functions)
Parameters
codec Pointer to a valid ce_codec
Definition at line 32 of file debug_codec.c.
References _dbg.
Referenced by test_ce_codec_B416K().
fsm_print_info()
void fsm_print_info (struct fsm * fsm)
#include <debug.h>
Print fsm information to STDOUT (name, config, state, ...)
Parameters
fsm Pointer to a valid fsm
Definition at line 33 of file fsm/debug.c.
References _dbg, fsm::config, fsm::driver, fsm::last, fsm::name, fsm::next, fsm::now, fsm_driver::start, fsm::state, and fsm_driver::stop.
Referenced by ce_driver_faf(), and test_fsm_driver_simple().
fsm_print_stats()
void fsm_print_stats (struct fsm * fsm)
#include <debug.h>
Print fsm stats to STDOUT (how many times each run-state has been executed/cycled)
Parameters
fsm Pointer to a valid fsm
Definition at line 55 of file fsm/debug.c.
References _dbg, FSM_ALL, FSM_ERROR, FSM_NEW, FSM_PAUSE, FSM_RUN, and fsm::stats.
Referenced by test_fsm_driver_simple().
rb_print_info()
void rb_print_info (struct rb * rb)
#include <debug.h>
Print rb information to STDOUT (size, head, tail, ...)
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
Definition at line 33 of file rb/debug.c.
References _dbg, rb::buffer, rb::driver, rb::head, rb::head_of, rb_driver::len, rb::size, rb::tail, and rb_driver::validate.
Referenced by s_decode(), s_encode(), test_ce_command_codec_B416K(), test_ce_driver_faf(), and test_rb_driver_overwrite().