yacup: B416K
B416K
Utilities » Command Engine » Available codecs
Description
Binary 4-byte + CRC-16/Kermit codec for ce util.
This implementation will use a rb to store or retrieve data, and will compose the data frame as follows: start_flag
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Macros
#define CE_CODEC_B416K_START_BYTE 0xEA
Byte used as start-flag in an encoded message.
Functions
int ce_codec_B416K (struct ce_codec *codec)
Codec initializer function for B416K type ce codec.
Function Documentation
ce_codec_B416K()
int ce_codec_B416K (struct ce_codec * codec)
#include <B416K.h>
Codec initializer function for B416K type ce codec.
Binary 4-byte + CRC-16/Kermit codec
Parameters
codec Pointer to a codec to initialize
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 509 of file B416K.c.
References _dbg, ce_codec::codec_sizeof, ce_codec_encoder::command, ce_codec_decoder::command, ce_codec_encoder::data, ce_codec_decoder::data, ce_codec::decode, ce_codec::encode, ce_codec_encoder::message, ce_codec_decoder::message, and ce_codec::name.
Referenced by test_ce_codec_B416K(), test_ce_command_codec_B416K(), test_ce_driver_faf(), and test_ce_initialization().