yacup: Ring-buffers
Ring-buffers
Yet another ring-buffer implementation.
Modules
Drivers
Operations driver for rb instances.
Data Structures
struct rb_op
Structure that defines valid operations on ring buffers.
struct rb
Structure that defines a ring buffer.
Functions
struct rb * rb_create (uint8_t *buf, size_t size, struct rb_op *(*driver)(void))
Create and initialize a ring-buffer. User needs to previously reserve a buffer.
void rb_destroy (struct rb *rb)
Destroy a ring-buffer and free its resources. User needs to destroy the buffer.
void rb_reset (struct rb *rb)
Reset a ring-buffer by cleaning its content and making it empty.
int rb_push (struct rb *rb, uint8_t byte)
Add a byte to a ring-buffer head, overwritting if needed.
int rb_pull (struct rb *rb, uint8_t *byte)
Read and delete a byte from a ring-buffer tail.
int rb_write (struct rb *rb, uint8_t byte, size_t position)
Write a byte by position on a ring-buffer, without updating head/tail.
int rb_read (struct rb *rb, uint8_t *byte, size_t position)
Read a byte by position from a ring-buffer, without updating head/tail.
size_t rb_size (struct rb *rb)
Returns max available size of a ring-buffer buffer.
size_t rb_len (struct rb *rb)
Returns available data size inside a ring-buffer.
uint8_t rb_full (struct rb *rb)
Check if a ring-buffer is full or not.
Detailed Description
Yet another ring-buffer implementation.
Ring buffer made easy (for me xD)
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Version
v1.0.0
Since
v1.0.0
Function Documentation
rb_create()
struct rb* rb_create (uint8_t * buf, size_t size, struct rb_op *(*)(void) driver)
#include <rb.h>
Create and initialize a ring-buffer. User needs to previously reserve a buffer.
Parameters
buf Buffer to store the data, created by the user
[in] size Size in bytes of the buffer
driver Pointer to a driver initializer function
Returns
One of:
Value Meaning
struct rb * Ok
NULL Error
Definition at line 42 of file rb.c.
References buffer, head, head_of, op, rb_op::reset, size, tail, and rb_op::validate.
Referenced by test_rb_driver_v1().
rb_destroy()
void rb_destroy (struct rb * rb)
#include <rb.h>
Destroy a ring-buffer and free its resources. User needs to destroy the buffer.
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
Definition at line 106 of file rb.c.
rb_full()
uint8_t rb_full (struct rb * rb)
#include <rb.h>
Check if a ring-buffer is full or not.
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
Returns
One of:
Value Meaning
== 0 Not empty or Error
!= 0 Empty
Definition at line 225 of file rb.c.
References rb_op::full, op, and rb_op::validate.
Referenced by test_rb_driver_v1().
rb_len()
size_t rb_len (struct rb * rb)
#include <rb.h>
Returns available data size inside a ring-buffer.
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
Returns
One of:
Value Meaning
== 0 0 or Error
!= 0 Valid size
Definition at line 210 of file rb.c.
References rb_op::len, op, and rb_op::validate.
Referenced by test_rb_driver_v1().
rb_pull()
int rb_pull (struct rb * rb, uint8_t * byte)
#include <rb.h>
Read and delete a byte from a ring-buffer tail.
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
byte Pointer to byte where to write the pushed value
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 150 of file rb.c.
References op, rb_op::pull, and rb_op::validate.
Referenced by test_rb_driver_v1().
rb_push()
int rb_push (struct rb * rb, uint8_t byte)
#include <rb.h>
Add a byte to a ring-buffer head, overwritting if needed.
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
[in] byte Byte to be pushed into the ring-buffer
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 135 of file rb.c.
References op, rb_op::push, and rb_op::validate.
Referenced by test_rb_driver_v1().
rb_read()
int rb_read (struct rb * rb, uint8_t * byte, size_t position)
#include <rb.h>
Read a byte by position from a ring-buffer, without updating head/tail.
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
byte Pointer to byte where to write the pushed value
[in] position Position to read, thinking as if ring-buffer is linear
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 180 of file rb.c.
References op, rb_op::read, and rb_op::validate.
Referenced by test_rb_driver_v1().
rb_reset()
void rb_reset (struct rb * rb)
#include <rb.h>
Reset a ring-buffer by cleaning its content and making it empty.
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
Definition at line 117 of file rb.c.
References op, rb_op::reset, and rb_op::validate.
Referenced by test_rb_driver_v1().
rb_size()
size_t rb_size (struct rb * rb)
#include <rb.h>
Returns max available size of a ring-buffer buffer.
Parameters
rb Pointer to a ring-buffer previously created with rb_create()
Returns
One of:
Value Meaning
== 0 0 or Error
!= 0 Valid size
Definition at line 195 of file rb.c.
References op, rb_op::size, and rb_op::validate.
rb_write()
int rb_write (struct rb * rb, uint8_t byte, size_t position)
#include <rb.h>
Write a byte by position on a ring-buffer, without updating head/tail.
Parameters
rb Pointer to a ring-buffer previously created with create()
[in] byte Byte to be written into the ring-buffer
[in] position Position to read, thinking as if ring-buffer is linear
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 165 of file rb.c.
References op, rb_op::validate, and rb_op::write.
Referenced by test_rb_driver_v1().