yacup: Simple FSM
Simple FSM
Finite state machines » Available FSM
A simple finite state machine for testing purposes.
Data Structures
struct fsm_simple_data
Internal data fsm_simple will use.
Functions
static int start (struct fsm *fsm)
Sate start: Prepare cycles variable.
static int state_1 (struct fsm *fsm)
State state_1: Stay here during 5 cycles variable counts.
static int stop (struct fsm *fsm)
State stop: Prepare anything before stopping the fsm.
int fsm_simple_setup (struct fsm *fsm)
Create and initialize a fsm_simple type FSM.
Detailed Description
A simple finite state machine for testing purposes.
This FSM just starts, execute state_1 5 times and finish
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Function Documentation
fsm_simple_setup()
int fsm_simple_setup (struct fsm * fsm)
#include <fsm_simple.h>
Create and initialize a fsm_simple type FSM.
This FSM just starts, execute state_1 5 times and finish
Parameters
fsm fsm pointer to work with. Valid if returns without errors
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 134 of file fsm_simple.c.
References fsm::config, fsm::data, FSM_ALL, FSM_ERROR, FSM_NEW, FSM_PAUSE, FSM_RUN, fsm::name, start(), fsm::start, fsm::state, fsm::stats, stop(), and fsm::stop.
Referenced by test_fsm_simple().
start()
static int start (struct fsm * fsm) static
#include <fsm_simple.c>
Sate start: Prepare cycles variable.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 63 of file fsm_simple.c.
References fsm::name, fsm::next, and state_1().
Referenced by fsm_simple_setup().
state_1()
static int state_1 (struct fsm * fsm) static
#include <fsm_simple.c>
State state_1: Stay here during 5 cycles variable counts.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 88 of file fsm_simple.c.
References fsm::name, fsm::next, and stop().
Referenced by start().
stop()
static int stop (struct fsm * fsm) static
#include <fsm_simple.c>
State stop: Prepare anything before stopping the fsm.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 120 of file fsm_simple.c.
References fsm::name.
Referenced by fsm_simple_setup(), and state_1().