yacup: Simple FSM
Simple FSM
Utilities » Finite state machine » Available drivers
Description
A simple finite state machine for testing purposes.
This FSM just starts, execute state_1 5 times and finish
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Data Structures
struct fsm_driver_simple_data
Internal data fsm_driver_simple will use.
Functions
int fsm_driver_simple (struct fsm *fsm)
Driver initializer function for fsm_driver_simple type FSM.
FSM States
static int start (struct fsm *fsm)
Prepare cycles variable.
static int state_1 (struct fsm *fsm)
Stay here during 5 counts of cycles variable.
static int stop (struct fsm *fsm)
Prepare anything before stopping the FSM.
Function Documentation
start()
static int start (struct fsm * fsm) static
#include <simple.c>
Prepare cycles variable.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 59 of file simple.c.
References _dbg, fsm::name, fsm::next, and state_1().
Referenced by fsm_driver_simple().
state_1()
static int state_1 (struct fsm * fsm) static
#include <simple.c>
Stay here during 5 counts of cycles variable.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 89 of file simple.c.
References _dbg, fsm::name, fsm::next, and stop().
Referenced by start().
stop()
static int stop (struct fsm * fsm) static
#include <simple.c>
Prepare anything before stopping the FSM.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Warning
Definition at line 126 of file simple.c.
References _dbg, and fsm::name.
Referenced by fsm_driver_simple(), and state_1().
fsm_driver_simple()
int fsm_driver_simple (struct fsm * fsm)
#include <simple.h>
Driver initializer function for fsm_driver_simple type FSM.
This FSM just starts, execute state_1 5 times and finish
Parameters
fsm Pointer to a fsm to work with
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 146 of file simple.c.
References _dbg, fsm::data, fsm::driver, fsm::name, fsm_driver::start, start(), and stop().
Referenced by test_fsm_driver_simple().