yacup: Interface
Interface
Finite state machines
Operations over fsm instances.
Data Structures
struct fsm
Structure that defines a finite state machine.
Enumerations
enum fsm_state {
FSM_NEW = 0, FSM_PAUSE = 1, FSM_RUN = 2, FSM_ERROR = 3,
FSM_ALL = 4
}
Valid states that a finite state machine can be in.
Functions
void fsm_enable (struct fsm *fsm)
Sets the enable bit, allowing this fsm to perform actions.
void fsm_disable (struct fsm *fsm)
Unsets the enable bit, disallowing this fsm to perform further actions.
void fsm_set_single (struct fsm *fsm)
Unsets the auto-restart bit, making this fsm to stop once completed.
void fsm_set_loop (struct fsm *fsm)
Sets the auto-restart bit, making this fsm to start again once completed.
void fsm_request_start (struct fsm *fsm)
Sets the started bit, making this fsm to start the next valid cycle.
void fsm_request_stop (struct fsm *fsm)
Unsets the started bit, making this fsm to stop the next valid cycle.
int fsm_do_cycle (struct fsm *fsm)
Stepper function (single cycle and exit, need outside controller loop)
Detailed Description
Operations over fsm instances.
Centralized functions to allow different FSM coexistence
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Enumeration Type Documentation
fsm_state
enum fsm_state
#include <fsm.h>
Valid states that a finite state machine can be in.
Enumerator
FSM_NEW
single-pass state only, just for initialization and checks
FSM_PAUSE
'Nothing to do' state. FSM possibly ended and no rearm bit was found
FSM_RUN
FSM core, where the magic happens.
FSM_ERROR
You're in a little trouble if you are here.
FSM_ALL
Not a real state, just for stats as a cycle counter.
Definition at line 64 of file fsm.h.
Function Documentation
fsm_disable()
void fsm_disable (struct fsm * fsm)
#include <fsm.h>
Unsets the enable bit, disallowing this fsm to perform further actions.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Definition at line 52 of file fsm.c.
References fsm::config.
fsm_do_cycle()
int fsm_do_cycle (struct fsm * fsm)
#include <fsm.h>
Stepper function (single cycle and exit, need outside controller loop)
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 92 of file fsm.c.
References fsm::config, FSM_ALL, FSM_ERROR, FSM_NEW, FSM_PAUSE, FSM_RUN, fsm::last, fsm::name, fsm::next, fsm::now, fsm::start, fsm::state, fsm::stats, and fsm::stop.
Referenced by test_fsm_simple().
fsm_enable()
void fsm_enable (struct fsm * fsm)
#include <fsm.h>
Sets the enable bit, allowing this fsm to perform actions.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Definition at line 44 of file fsm.c.
References fsm::config.
Referenced by test_fsm_simple().
fsm_request_start()
void fsm_request_start (struct fsm * fsm)
#include <fsm.h>
Sets the started bit, making this fsm to start the next valid cycle.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Definition at line 76 of file fsm.c.
References fsm::config.
Referenced by test_fsm_simple().
fsm_request_stop()
void fsm_request_stop (struct fsm * fsm)
#include <fsm.h>
Unsets the started bit, making this fsm to stop the next valid cycle.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Definition at line 84 of file fsm.c.
References fsm::config.
fsm_set_loop()
void fsm_set_loop (struct fsm * fsm)
#include <fsm.h>
Sets the auto-restart bit, making this fsm to start again once completed.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Definition at line 68 of file fsm.c.
References fsm::config.
Referenced by test_fsm_simple().
fsm_set_single()
void fsm_set_single (struct fsm * fsm)
#include <fsm.h>
Unsets the auto-restart bit, making this fsm to stop once completed.
Parameters
fsm Pointer to a FSM. Use dedicated fsm setup function before
Definition at line 60 of file fsm.c.
References fsm::config.