yacup: Interface
Interface
Utilities » Ring-buffer
Description
Complete API documentation for ring buffers setup, instantiation and usage.
Todo:
Write a description/@details
Author
CieNTi cient.nosp@m.i@ci.nosp@m.enti..nosp@m.com
Date
2020
Data Structures
struct rb_driver
Structure that defines valid operations on ring buffers.
struct rb
Structure that defines a ring buffer.
Functions
int rb_init (struct rb *rb, int(*rb_driver_init)(struct rb *))
Initializes a rb
void rb_reset (struct rb *rb)
Reset a ring-buffer by cleaning its content and making it empty.
int rb_push (struct rb *rb, uint8_t byte)
Add a byte to a ring-buffer head, overwritting if needed.
int rb_pull (struct rb *rb, uint8_t *byte)
Read and delete a byte from a ring-buffer tail.
int rb_write (struct rb *rb, uint8_t byte, size_t position)
Write a byte by position on a ring-buffer, without updating head/tail.
int rb_read (struct rb *rb, uint8_t *byte, size_t position)
Read a byte by position from a ring-buffer, without updating head/tail.
size_t rb_size (struct rb *rb)
Returns max available size of a ring-buffer buffer.
size_t rb_len (struct rb *rb)
Returns available data size inside a ring-buffer.
uint8_t rb_full (struct rb *rb)
Check if a ring-buffer is full or not.
Function Documentation
rb_init()
int rb_init (struct rb * rb, int(*)(struct rb *) rb_driver_init)
#include <rb.h>
Initializes a rb
Checks and initializes rb common data, then calls the lower level init function passed by argument.
Parameters
rb Pointer to a RB to initialize
rb_driver_init Pointer to a driver initializer function
Returns
One of:
Value Meaning
struct rb * Ok
NULL Error
Definition at line 31 of file rb.c.
References _dbg, rb::buffer, rb::driver, rb::head, rb::head_of, rb_driver::name, rb_driver::reset, rb::size, rb::tail, and rb_driver::validate.
Referenced by ce_channel_init(), test_ce_codec_B416K(), test_ce_command_codec_B416K(), and test_rb_driver_overwrite().
rb_reset()
void rb_reset (struct rb * rb)
#include <rb.h>
Reset a ring-buffer by cleaning its content and making it empty.
Parameters
rb Pointer to a correctly initialized RB
Definition at line 97 of file rb.c.
References _dbg, rb::driver, rb_driver::reset, and rb_driver::validate.
Referenced by test_rb_driver_overwrite().
rb_push()
int rb_push (struct rb * rb, uint8_t byte)
#include <rb.h>
Add a byte to a ring-buffer head, overwritting if needed.
Parameters
rb Pointer to a correctly initialized RB
[in] byte Byte to be pushed into the ring-buffer
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 121 of file rb.c.
References _dbg, rb::driver, rb_driver::push, and rb_driver::validate.
Referenced by test_rb_driver_overwrite().
rb_pull()
int rb_pull (struct rb * rb, uint8_t * byte)
#include <rb.h>
Read and delete a byte from a ring-buffer tail.
Parameters
rb Pointer to a correctly initialized RB
byte Pointer to byte where to write the pushed value
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 142 of file rb.c.
References _dbg, rb::driver, rb_driver::pull, and rb_driver::validate.
Referenced by test_rb_driver_overwrite().
rb_write()
int rb_write (struct rb * rb, uint8_t byte, size_t position)
#include <rb.h>
Write a byte by position on a ring-buffer, without updating head/tail.
Parameters
rb Pointer to a correctly initialized RB
[in] byte Byte to be written into the ring-buffer
[in] position Position to read, thinking as if ring-buffer is linear
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 163 of file rb.c.
References _dbg, rb::driver, rb_driver::validate, and rb_driver::write.
Referenced by test_rb_driver_overwrite().
rb_read()
int rb_read (struct rb * rb, uint8_t * byte, size_t position)
#include <rb.h>
Read a byte by position from a ring-buffer, without updating head/tail.
Parameters
rb Pointer to a correctly initialized RB
byte Pointer to byte where to write the pushed value
[in] position Position to read, thinking as if ring-buffer is linear
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 184 of file rb.c.
References _dbg, rb::driver, rb_driver::read, and rb_driver::validate.
Referenced by test_rb_driver_overwrite().
rb_size()
size_t rb_size (struct rb * rb)
#include <rb.h>
Returns max available size of a ring-buffer buffer.
Parameters
rb Pointer to a correctly initialized RB
Returns
One of:
Value Meaning
== 0 0 or Error
!= 0 Valid size
Definition at line 205 of file rb.c.
References _dbg, rb::driver, rb_driver::size, and rb_driver::validate.
rb_len()
size_t rb_len (struct rb * rb)
#include <rb.h>
Returns available data size inside a ring-buffer.
Parameters
rb Pointer to a correctly initialized RB
Returns
One of:
Value Meaning
== 0 0 or Error
!= 0 Valid size
Definition at line 226 of file rb.c.
References _dbg, rb::driver, rb_driver::len, and rb_driver::validate.
Referenced by test_rb_driver_overwrite().
rb_full()
uint8_t rb_full (struct rb * rb)
#include <rb.h>
Check if a ring-buffer is full or not.
Parameters
rb Pointer to a correctly initialized RB
Returns
One of:
Value Meaning
== 0 Not empty or Error
!= 0 Empty
Definition at line 247 of file rb.c.
References _dbg, rb::driver, rb_driver::full, and rb_driver::validate.
Referenced by test_rb_driver_overwrite().