yacup: rb_driver Struct Reference
rb_driver Struct Reference
Utilities » Ring-buffer » Interface
Structure that defines valid operations on ring buffers.
#include <driver.h>
Data Fields
char * name
ASCII name of this driver.
int(* validate)(struct rb *rb)
Checks if the ring-buffer is valid or not.
void(* reset)(struct rb *rb)
Reset a ring-buffer by cleaning its content and making it empty.
int(* push)(struct rb *rb, uint8_t byte)
Add a byte to a ring-buffer head, overwritting if needed.
int(* pull)(struct rb *rb, uint8_t *byte)
Read and delete a byte from a ring-buffer tail.
int(* write)(struct rb *rb, uint8_t byte, size_t position)
Write a byte by position on a ring-buffer, without updating head/tail.
int(* read)(struct rb *rb, uint8_t *byte, size_t position)
Read a byte by position from a ring-buffer, without updating head/tail.
size_t(* size)(struct rb *rb)
Returns max available size of a ring-buffer buffer.
size_t(* len)(struct rb *rb)
Returns available data size inside a ring-buffer.
uint8_t(* full)(struct rb *rb)
Check if a ring-buffer is full or not.
Detailed Description
Structure that defines valid operations on ring buffers.
Definition at line 40 of file rb/yacup/rb/driver.h.
Field Documentation
validate
int(* rb_driver::validate) (struct rb *rb)
Checks if the ring-buffer is valid or not.
Parameters
rb Pointer to a ring-buffer previously created with create()
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 58 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), rb_full(), rb_init(), rb_len(), rb_print_info(), rb_pull(), rb_push(), rb_read(), rb_reset(), rb_size(), and rb_write().
reset
void(* rb_driver::reset) (struct rb *rb)
Reset a ring-buffer by cleaning its content and making it empty.
Parameters
rb Pointer to a ring-buffer previously created with create()
Definition at line 65 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), rb_init(), and rb_reset().
push
int(* rb_driver::push) (struct rb *rb, uint8_t byte)
Add a byte to a ring-buffer head, overwritting if needed.
Parameters
rb Pointer to a ring-buffer previously created with create()
[in] byte Byte to be pushed into the ring-buffer
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 79 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), and rb_push().
pull
int(* rb_driver::pull) (struct rb *rb, uint8_t *byte)
Read and delete a byte from a ring-buffer tail.
Parameters
rb Pointer to a ring-buffer previously created with create()
byte Pointer to byte where to write the pushed value
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 93 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), and rb_pull().
write
int(* rb_driver::write) (struct rb *rb, uint8_t byte, size_t position)
Write a byte by position on a ring-buffer, without updating head/tail.
Parameters
rb Pointer to a ring-buffer previously created with create()
[in] byte Byte to be written into the ring-buffer
[in] position Position to read, thinking as if ring-buffer is linear
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 111 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), and rb_write().
read
int(* rb_driver::read) (struct rb *rb, uint8_t *byte, size_t position)
Read a byte by position from a ring-buffer, without updating head/tail.
Parameters
rb Pointer to a ring-buffer previously created with create()
byte Pointer to byte where to write the pushed value
[in] position Position to read, thinking as if ring-buffer is linear
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 129 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), and rb_read().
size
size_t(* rb_driver::size) (struct rb *rb)
Returns max available size of a ring-buffer buffer.
Parameters
rb Pointer to a ring-buffer previously created with create()
Returns
One of:
Value Meaning
== 0 0 or Error
!= 0 Valid size
Definition at line 142 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), and rb_size().
len
size_t(* rb_driver::len) (struct rb *rb)
Returns available data size inside a ring-buffer.
Parameters
rb Pointer to a ring-buffer previously created with create()
Returns
One of:
Value Meaning
== 0 0 or Error
!= 0 Valid size
Definition at line 155 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), rb_len(), and rb_print_info().
full
uint8_t(* rb_driver::full) (struct rb *rb)
Check if a ring-buffer is full or not.
Parameters
rb Pointer to a ring-buffer previously created with create()
Returns
One of:
Value Meaning
== 0 Not empty or Error
!= 0 Empty
Definition at line 168 of file rb/yacup/rb/driver.h.
Referenced by rb_driver_overwrite(), and rb_full().
The documentation for this struct was generated from the following file:
rb/yacup/rb/driver.h