yacup: ce_codec_encoder Struct Reference
ce_codec_encoder Struct Reference
Utilities » Command Engine » Interface
Structure that defines a ce codec encoder operations.
#include <codec.h>
Data Fields
size_t(* data)(enum ce_data_type type, void *data, size_t num_data, struct rb *rb)
Encodes a defined type data and pushes it into a ring-buffer.
size_t(* command)(struct ce_command *command, struct ce_command_argument *argument[], struct rb *rb_data)
Encodes a command as a data-block into a rb.
int(* message)(struct rb *rb_data, struct rb *rb_msg)
Takes an input rb with raw data, encodes it as a message, and puts it back into an output rb, ready to be decoded.
Detailed Description
Structure that defines a ce codec encoder operations.
Definition at line 40 of file codec.h.
Field Documentation
data
size_t(* ce_codec_encoder::data) (enum ce_data_type type, void *data, size_t num_data, struct rb *rb)
Encodes a defined type data and pushes it into a ring-buffer.
Parameters
type One of CE_DATA_* data types
data Pointer where the source data to encode is located
num_data Number of data entities to encode
rb Pointer to a destination ring-buffer
Returns
One of:
Value Meaning
== 0 No encoded data
> 0 Number of encoded data entities
Definition at line 56 of file codec.h.
Referenced by ce_codec_B416K(), and ce_codec_init().
command
size_t(* ce_codec_encoder::command) (struct ce_command *command, struct ce_command_argument *argument[], struct rb *rb_data)
Encodes a command as a data-block into a rb.
Parameters
command Pointer to a command to be encoded
argument Command arguments data to encode
rb_data Pointer to a destination data block ring-buffer
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 73 of file codec.h.
Referenced by ce_codec_B416K(), ce_codec_init(), s_encode(), and test_ce_command_codec_B416K().
message
int(* ce_codec_encoder::message) (struct rb *rb_data, struct rb *rb_msg)
Takes an input rb with raw data, encodes it as a message, and puts it back into an output rb, ready to be decoded.
Parameters
rb_data Pointer to a ring-buffer containing the data
rb_msg Pointer to a ring-buffer to save the message in
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 90 of file codec.h.
Referenced by ce_codec_B416K(), ce_codec_init(), and s_encode().
The documentation for this struct was generated from the following file:
codec.h