yacup: ce_codec_decoder Struct Reference
ce_codec_decoder Struct Reference
Utilities » Command Engine » Interface
Structure that defines a ce codec encoder operations.
#include <codec.h>
Data Fields
size_t(* data)(struct rb *rb, enum ce_data_type type, void *data, size_t num_data)
Pulls and decodes a defined type data from a ring-buffer and saves it into a pointed variable.
size_t(* command)(struct rb *rb_data, struct ce_command_set *cmd_set, struct ce_command **command)
Decodes a data-block into a validated command with arguments.
int(* message)(struct rb *rb_msg, struct rb *rb_data)
Takes an input rb with an encoded message, decodes it, extract its data packet, and puts into a destination rb
Detailed Description
Structure that defines a ce codec encoder operations.
Definition at line 96 of file codec.h.
Field Documentation
data
size_t(* ce_codec_decoder::data) (struct rb *rb, enum ce_data_type type, void *data, size_t num_data)
Pulls and decodes a defined type data from a ring-buffer and saves it into a pointed variable.
Parameters
rb Pointer to a source ring-buffer with encoded data
type One of CE_DATA_* data types
data Pointer to a destination for decoded data
num_data Number of data entities to decode
Returns
One of:
Value Meaning
== 0 No decoded data
> 0 Number of decoded data entities
Definition at line 113 of file codec.h.
Referenced by ce_codec_B416K(), and ce_codec_init().
command
size_t(* ce_codec_decoder::command) (struct rb *rb_data, struct ce_command_set *cmd_set, struct ce_command **command)
Decodes a data-block into a validated command with arguments.
Todo:
Is this the parser to listener call?
Parameters
rb_data Pointer to a destination data block ring-buffer
cmd_set Set of commands where to search for commands
command Pointer to command holding the decoded one, or NULL
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 131 of file codec.h.
Referenced by ce_codec_B416K(), ce_codec_init(), and s_decode().
message
int(* ce_codec_decoder::message) (struct rb *rb_msg, struct rb *rb_data)
Takes an input rb with an encoded message, decodes it, extract its data packet, and puts into a destination rb
Parameters
rb_msg Pointer to a ring-buffer containing the message
rb_data Pointer to a ring-buffer to save the data in
Returns
One of:
Value Meaning
== 0 Ok
!= 0 Error
Definition at line 148 of file codec.h.
Referenced by ce_codec_B416K(), ce_codec_init(), and s_decode().
The documentation for this struct was generated from the following file:
codec.h