yacup: fsm Struct Reference
fsm Struct Reference
Finite state machines » Interface
Structure that defines a finite state machine.
#include <fsm.h>
Data Fields
char * name
Name of the finite state machine, useful to track many of them.
uint8_t config
Saves finite state machine configuration (enabled, auto, ...)
enum fsm_state state
Current state of the FSM.
size_t stats [5]
Hold each state stats as a count of passed cycles for each one.
void * data
Internal data as a pointer to void, managed by the FSM itself.
int(* start)(struct fsm *fsm)
State function executed to start the FSM.
int(* stop)(struct fsm *fsm)
State function executed to stop, before pause or restart.
int(* last)(struct fsm *fsm)
Saves previously executed state.
int(* now)(struct fsm *fsm)
Current FSM state, in execution.
int(* next)(struct fsm *fsm)
Next state to be executed.
Detailed Description
Structure that defines a finite state machine.
Definition at line 92 of file fsm.h.
Field Documentation
start
int(* start) (struct fsm *fsm)
State function executed to start the FSM.
Warning
It is mandatory, otherwise the FSM will fail miserably
Definition at line 123 of file fsm.h.
Referenced by fsm_do_cycle(), fsm_print_info(), and fsm_simple_setup().
The documentation for this struct was generated from the following file:
fsm.h